// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qlegis.Models;

#nullable disable

namespace Qlegis.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220927015935_Criacao-Inicial")]
    partial class CriacaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Qlegis.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("longtext")
                        .HasColumnName("ConfirmPassword");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("FirstName");

                    b.Property<string>("ImageAvatarPerfil")
                        .HasColumnType("longtext")
                        .HasColumnName("ImageAvatarPerfil");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("LastName");

                    b.Property<string>("NumberPhoneCell")
                        .HasColumnType("longtext")
                        .HasColumnName("NumberPhoneCell");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<string>("State")
                        .HasColumnType("longtext")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
